"""Parallel and composed checks retain complete, independent Contract evidence."""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path
from threading import Barrier, Lock

import pytest

from scripts.contracts import generate_gateway_contracts as runner

OWNED = "# @generated by scripts/contracts/generate_gateway_contracts.py\n"


@pytest.fixture
def specs() -> tuple[runner.ContractSpec, ...]:
    return runner.discover_contracts()[:4]


def _artifacts(spec: runner.ContractSpec) -> dict[Path, str]:
    return {path: f"{OWNED}{spec.wire_name}: {path.name}\n" for path in spec.outputs}


def _existing_tree(destination: Path, source: Path) -> tuple[Path, Path, Path]:
    previous = destination / source.relative_to(runner.ROOT)
    previous.parent.mkdir(parents=True)
    previous.write_text(f"{OWNED}previous\n", encoding="utf-8")
    orphan = previous.with_name("obsolete.py")
    orphan.write_text(f"{OWNED}orphan\n", encoding="utf-8")
    unowned = previous.with_name("manual.py")
    unowned.write_text("hand maintained\n", encoding="utf-8")
    return previous, orphan, unowned


def test_workers_preserve_serial_tree_and_bound_active_compilers(
    specs: tuple[runner.ContractSpec, ...], monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(runner, "render_generic", lambda spec, **_: _artifacts(spec))
    serial = runner.render_tree(specs, profile="verification")
    barrier = Barrier(2)
    lock = Lock()
    active = 0
    peak = 0
    seen: list[str] = []

    def concurrent_render(spec: runner.ContractSpec, **_: object) -> dict[Path, str]:
        nonlocal active, peak
        with lock:
            active += 1
            peak = max(peak, active)
            seen.append(spec.wire_name)
        barrier.wait(timeout=10)
        try:
            return _artifacts(spec)
        finally:
            with lock:
                active -= 1

    monkeypatch.setattr(runner, "render_generic", concurrent_render)
    parallel = runner.render_tree(tuple(reversed(specs)), profile="verification", jobs=2)
    assert parallel == serial
    assert list(parallel) == list(serial)
    assert peak == 2
    assert Counter(seen) == Counter(spec.wire_name for spec in specs)


@pytest.mark.parametrize("mode", ["check-determinism", "write-determinism"])
def test_composed_mode_renders_every_contract_twice_before_publication(
    tmp_path: Path,
    specs: tuple[runner.ContractSpec, ...],
    monkeypatch: pytest.MonkeyPatch,
    mode: runner.Mode,
) -> None:
    previous, orphan, unowned = _existing_tree(tmp_path, specs[0].outputs[0])
    original = previous.read_text(encoding="utf-8")
    seen: list[str] = []

    def render(spec: runner.ContractSpec, **_: object) -> dict[Path, str]:
        assert previous.read_text(encoding="utf-8") == original
        assert orphan.exists()
        seen.append(spec.wire_name)
        return _artifacts(spec)

    monkeypatch.setattr(runner, "render_generic", render)
    result = runner.run(mode, specs, profile="verification", output_root=tmp_path, jobs=2)
    assert Counter(seen) == Counter({spec.wire_name: 2 for spec in specs})
    assert unowned.read_text(encoding="utf-8") == "hand maintained\n"
    if mode == "write-determinism":
        assert result == 0
        assert previous.read_text(encoding="utf-8") == _artifacts(specs[0])[specs[0].outputs[0]]
        assert not orphan.exists()
        assert (tmp_path / runner.REGISTRATION_OUTPUT.relative_to(runner.ROOT)).exists()
        assert (tmp_path / runner.COMPATIBILITY_MANIFEST_OUTPUT.relative_to(runner.ROOT)).exists()
    else:
        assert result == 1
        assert previous.read_text(encoding="utf-8") == original
        assert orphan.exists()


@pytest.mark.parametrize("defect", [None, "stale", "orphan"])
def test_composed_check_detects_stale_output_and_orphans_without_writing(
    tmp_path: Path,
    specs: tuple[runner.ContractSpec, ...],
    monkeypatch: pytest.MonkeyPatch,
    defect: str | None,
) -> None:
    monkeypatch.setattr(runner, "render_generic", lambda spec, **_: _artifacts(spec))
    assert runner.run("write", specs, profile="verification", output_root=tmp_path) == 0
    if defect == "stale":
        target = tmp_path / specs[0].outputs[0].relative_to(runner.ROOT)
        target.write_text("stale\n", encoding="utf-8")
    elif defect == "orphan":
        target = tmp_path / (runner.PYTHON_OUTPUT_ROOT / "obsolete.py").relative_to(runner.ROOT)
        target.write_text(f"{OWNED}orphan\n", encoding="utf-8")
    before = {path: path.read_bytes() for path in tmp_path.rglob("*") if path.is_file()}
    assert runner.run(
        "check-determinism", specs, profile="verification", output_root=tmp_path, jobs=2
    ) == int(defect is not None)
    assert {path: path.read_bytes() for path in tmp_path.rglob("*") if path.is_file()} == before


@pytest.mark.parametrize("mode", ["check-determinism", "write-determinism"])
@pytest.mark.parametrize("difference", ["bytes", "path"])
def test_nondeterministic_second_render_preserves_output_and_orphans(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    mode: runner.Mode,
    difference: str,
) -> None:
    source = runner.PYTHON_OUTPUT_ROOT / "probe.py"
    previous, orphan, unowned = _existing_tree(tmp_path, source)
    before = {path: path.read_bytes() for path in (previous, orphan, unowned)}
    calls = 0

    def render(*_: object, **__: object) -> dict[Path, str]:
        nonlocal calls
        calls += 1
        if calls == 1:
            return {source: "first\n"}
        return {source: "second\n"} if difference == "bytes" else {}

    monkeypatch.setattr(runner, "render_tree", render)
    assert runner.run(mode, (), profile="verification", output_root=tmp_path, jobs=2) == 1
    assert calls == 2
    assert {path: path.read_bytes() for path in (previous, orphan, unowned)} == before


@pytest.mark.parametrize("failure_pass", [1, 2])
def test_parallel_compiler_failure_preserves_complete_previous_tree(
    tmp_path: Path,
    specs: tuple[runner.ContractSpec, ...],
    monkeypatch: pytest.MonkeyPatch,
    failure_pass: int,
) -> None:
    _existing_tree(tmp_path, specs[0].outputs[0])
    before = {path: path.read_bytes() for path in tmp_path.rglob("*") if path.is_file()}
    calls: Counter[str] = Counter()
    lock = Lock()

    def render(spec: runner.ContractSpec, **_: object) -> dict[Path, str]:
        with lock:
            calls[spec.wire_name] += 1
            count = calls[spec.wire_name]
        if spec == specs[-1] and count == failure_pass:
            raise RuntimeError("synthetic compiler failure")
        return _artifacts(spec)

    monkeypatch.setattr(runner, "render_generic", render)
    with pytest.raises(RuntimeError, match="synthetic compiler failure"):
        runner.run("write-determinism", specs, profile="verification", output_root=tmp_path, jobs=2)
    assert {path: path.read_bytes() for path in tmp_path.rglob("*") if path.is_file()} == before


@pytest.mark.parametrize("jobs", [0, -1, runner.MAX_GENERATOR_JOBS + 1, True, 1.5])
def test_invalid_worker_count_is_rejected_before_generation(
    jobs: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    def unexpected_render(*_: object, **__: object) -> dict[Path, str]:
        pytest.fail("invalid worker count reached rendering")

    monkeypatch.setattr(runner, "render_tree", unexpected_render)
    with pytest.raises(runner.ContractConfigurationError, match="jobs must be between"):
        runner.run("check", (), jobs=jobs)


@pytest.mark.parametrize("jobs", ["0", "-1", "33", "1.5", "invalid"])
def test_cli_rejects_invalid_worker_count(jobs: str, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(sys, "argv", ["generate_gateway_contracts.py", "--check", "--jobs", jobs])
    with pytest.raises(SystemExit) as error:
        runner.main()
    assert error.value.code == 2


@pytest.mark.parametrize("mode", ["check-determinism", "write-determinism"])
def test_cli_passes_composed_mode_and_workers_to_runner(
    mode: runner.Mode, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls: list[tuple[runner.Mode, dict[str, object]]] = []
    monkeypatch.setattr(sys, "argv", ["generate_gateway_contracts.py", f"--{mode}", "--jobs", "4"])
    monkeypatch.setattr(runner, "discover_contracts", lambda: ())

    def run(selected_mode: runner.Mode, *_: object, **options: object) -> int:
        calls.append((selected_mode, options))
        return 7

    monkeypatch.setattr(runner, "run", run)
    assert runner.main() == 7
    assert calls == [(mode, {"profile": "production", "output_root": None, "jobs": 4})]
