import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ref } from 'vue'
import { downloadText } from '@/utils/browser'
import type { ReadMessageText } from '@/utils/chat/historyMessageContent'

import { buildChatMarkdown, useChatMarkdownExport } from './useChatMarkdownExport'

vi.mock('@/utils/browser', () => ({ downloadText: vi.fn() }))
beforeEach(() => vi.mocked(downloadText).mockClear())
import type { ChatRenderedMessage } from '@/types/chat'

describe('buildChatMarkdown', () => {
  it('exports subagent completion messages as readable summaries, not raw JSON', () => {
    const json = JSON.stringify({
      type: 'subagent_completion',
      parent_session_key: 'agent:main:webchat:wo01onmp',
      child_session_key: 'agent:main:subagent:4dd8059d',
      status: 'succeeded',
      terminal_reason: 'completed',
      result: {
        text: 'OK',
      },
    })

    const markdown = buildChatMarkdown({
      title: '烟火App创意设计',
      exportedAt: '2026-06-29T07:30:02.759Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'subagent',
        roleLabel: 'Sub-agent',
        text: json,
        timeStr: '3m ago',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('## Sub-agent')
    expect(markdown).toContain('Subagent agent:main:subagent:4dd8059d completed with status succeeded')
    expect(markdown).toContain('Result:\nOK')
    expect(markdown).not.toContain('"type": "subagent_completion"')
    expect(markdown).not.toContain('"parent_session_key"')
  })

  it('exports protocol-shaped documentation without truncating it', () => {
    const text = [
      'Document `<tool_calls>` inline.',
      '```xml',
      '<tool_calls><invoke name="demo"></invoke></tool_calls>',
      '```',
      'Keep `<｜DSML｜tool_calls>` too.',
      '<details><summary>View areas around line 10</summary>Visible note.</details>',
      'Final suffix.',
    ].join('\n')

    const markdown = buildChatMarkdown({
      title: 'Protocol documentation',
      exportedAt: '2026-07-15T14:39:00.000Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'assistant',
        roleLabel: 'Assistant',
        text,
        timeStr: 'now',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain(text)
    expect(markdown).toContain('Final suffix.')
    expect(markdown).toContain('> Content generated by AI, for reference only.')
  })

  it('omits legacy assistant boundary sentinels while retaining substantive text', () => {
    const markdown = buildChatMarkdown({
      title: 'Legacy silent delivery',
      exportedAt: '2026-08-11T10:00:00.000Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'assistant',
        roleLabel: 'Assistant',
        text: 'NO_REPLY\nVisible answer.\nHEARTBEAT_OK',
        timeStr: 'now',
        turnRunKind: 'goal',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('Visible answer.')
    expect(markdown).not.toContain('NO_REPLY')
    expect(markdown).not.toContain('HEARTBEAT_OK')
  })

  it('exports only explicit answer text from a failed terminal turn', () => {
    const markdown = buildChatMarkdown({
      title: 'Failed tool projection',
      exportedAt: '2026-08-11T10:00:00.000Z',
      aiGeneratedLabel: 'AI generated',
      messages: [{
        displayRole: 'assistant',
        roleLabel: 'Assistant',
        text: 'Checking the repository.\n\nThe final answer.',
        terminalFailure: true,
        turnOutcome: {
          turnId: 'turn-failed-projection',
          status: 'failed',
        },
        timelineItems: [
          {
            type: 'text',
            key: 'narration',
            html: 'Checking the repository.',
            rawText: 'Checking the repository.',
            presentation: 'intermediate',
          },
          {
            type: 'text',
            key: 'answer',
            html: 'The final answer.',
            rawText: 'The final answer.',
            presentation: 'answer',
          },
        ],
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('The final answer.')
    expect(markdown).not.toContain('Checking the repository.')
  })

  it('retains mixed sentinel-looking text exported from an ordinary user turn', () => {
    const markdown = buildChatMarkdown({
      title: 'Literal marker documentation',
      exportedAt: '2026-08-11T10:00:00.000Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'assistant',
        roleLabel: 'Assistant',
        text: 'NO_REPLY\nLiteral explanation',
        timeStr: 'now',
        turnInputMode: 'user',
        turnRunKind: 'default',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('NO_REPLY\nLiteral explanation')
  })

  it('exports the authoritative routed model instead of inferring it from UI cells', () => {
    const markdown = buildChatMarkdown({
      title: 'Historical route',
      exportedAt: '2026-08-25T00:00:00.000Z',
      aiGeneratedLabel: 'AI generated',
      messages: [{
        displayRole: 'router',
        roleLabel: 'Router',
        text: '',
        timeStr: '',
        isRouterStrip: true,
        routerSelectedModel: 'historical/authoritative-model',
        winnerIdx: 0,
        gridCells: [{
          kind: 'real',
          tier: 'c1',
          tiers: ['c1'],
          displayName: 'stale-model',
          model: 'current/stale-model',
        }],
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('> Router selected historical/authoritative-model')
    expect(markdown).not.toContain('current/stale-model')
  })
})


describe('complete Markdown export', () => {
  const body = '0123456789'.repeat(2048) + 'EXPECTED_FINAL_TAIL'
  function fixture() {
    const messages = ref<ChatRenderedMessage[]>([{
      role: 'user', displayRole: 'user', roleLabel: 'User', text: body.slice(0, 16384),
      timeStr: '', showHeader: false, messageId: 'long-user', previewComplete: false,
      contentRef: { version: 1, sessionKey: 'session-a', sessionId: 'physical-a', messageId: 'long-user',
        source: 'active', view: 'display', revision: 'revision-a' },
    }])
    const session = ref('session-a:0')
    const read = vi.fn<ReadMessageText>(async () => body)
    const options = { messages, currentTitle: ref('Long history'), aiGeneratedLabel: ref('AI generated'),
      sessionIdentity: () => session.value, readMessageText: read }
    return { ...useChatMarkdownExport(options), messages, options, session, read }
  }

  it('downloads the complete body without changing the bounded transcript projection', async () => {
    const { exportMarkdown, messages } = fixture()
    expect(await exportMarkdown()).toBe(true)
    expect(downloadText).toHaveBeenCalledOnce()
    expect(vi.mocked(downloadText).mock.calls[0]?.[2]).toContain(body)
    expect(messages.value[0]?.text).toBe(body.slice(0, 16384))
  })

  it('restores explicit assistant answer boundaries before formatting', async () => {
    const { exportMarkdown, messages, read } = fixture()
    const note = 'Investigating. '
    const answer = 'Final answer 😀'.repeat(2000) + 'ANSWER_TAIL'
    messages.value = [{ ...messages.value[0]!, role: 'assistant', displayRole: 'assistant',
      text: note + answer.slice(0, 50),
      historyPayloadPreview: { textUtf16Lengths: [note.length, answer.length] },
      timelineItems: [
        { type: 'text', key: 'note', rawText: note, html: '', presentation: 'intermediate', activityOrder: 1 },
        { type: 'text', key: 'answer', rawText: answer.slice(0, 50), html: '', presentation: 'answer', activityOrder: 3 },
      ],
    }]
    read.mockResolvedValue(note + answer)
    expect(await exportMarkdown()).toBe(true)
    const markdown = vi.mocked(downloadText).mock.calls[0]?.[2]
    expect(markdown).toContain(answer)
    expect(markdown).not.toContain(note)
  })

  it('refuses to export a partial conversation when one body read fails', async () => {
    const { exportMarkdown, messages, read } = fixture()
    messages.value.push({ ...messages.value[0]!, messageId: 'second' })
    read.mockResolvedValueOnce(body).mockRejectedValueOnce(new Error('incomplete range'))
    expect(await exportMarkdown()).toBe(false)
    expect(downloadText).not.toHaveBeenCalled()
  })

  it('refuses a truncated explicit timeline that cannot be reconstructed', async () => {
    const { exportMarkdown, messages } = fixture()
    messages.value[0] = { ...messages.value[0]!, role: 'assistant', displayRole: 'assistant',
      historyPayloadPreview: { textUtf16Lengths: [body.length + 1] },
      timelineItems: [{ type: 'text', key: 'answer', rawText: 'preview', html: '', presentation: 'answer' }],
    }
    expect(await exportMarkdown()).toBe(false)
    expect(downloadText).not.toHaveBeenCalled()
  })

  it.each(['session', 'epoch', 'revision', 'transcript'] as const)('discards an export after %s changes', async change => {
    const { exportMarkdown, messages, session, read } = fixture()
    let resolve!: (text: string) => void
    read.mockImplementation(() => new Promise(done => { resolve = done }))
    const request = exportMarkdown()
    if (change === 'session') { session.value = 'session-b:0'; session.value = 'session-a:0' }
    if (change === 'epoch') session.value = 'session-a:1'
    if (change === 'revision') messages.value[0]!.contentRef!.revision = 'new-revision'
    if (change === 'transcript') messages.value = []
    resolve(body)
    expect(await request).toBe(false)
    expect(downloadText).not.toHaveBeenCalled()
  })

  it('supersedes a pending export without downloading its late result', async () => {
    const { exportMarkdown, read } = fixture()
    let resolve!: (text: string) => void
    read.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const first = exportMarkdown()
    expect(await exportMarkdown()).toBe(true)
    resolve('STALE')
    expect(await first).toBe(false)
    expect(downloadText).toHaveBeenCalledOnce()
    expect(vi.mocked(downloadText).mock.calls[0]?.[2]).toContain(body)
  })

  it('exports complete bodies directly even if a details-only contentRef exists', async () => {
    const { exportMarkdown, messages, read } = fixture()
    messages.value[0]!.previewComplete = true
    messages.value[0]!.text = body
    expect(await exportMarkdown()).toBe(true)
    expect(read).not.toHaveBeenCalled()
    expect(vi.mocked(downloadText).mock.calls[0]?.[2]).toContain(body)
  })
})
