#!/usr/bin/env python3
"""Generate the sessions.list Python and TypeScript Contract artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "contracts/gateway/v4/sessions/sessions-list.schema.json"
PYTHON_OUTPUT = ROOT / "src/opensquilla/contracts/generated/v4/sessions_list.py"
PYTHON_METADATA_OUTPUT = (
    ROOT / "src/opensquilla/contracts/generated/v4/sessions_list_metadata.py"
)
TYPESCRIPT_OUTPUT = (
    ROOT / "opensquilla-webui/src/contracts/generated/v4/sessionsList.ts"
)
VALIDATOR_OUTPUT = (
    ROOT / "opensquilla-webui/src/contracts/generated/v4/sessionsListValidators.cjs"
)
VALIDATOR_DECLARATIONS_OUTPUT = VALIDATOR_OUTPUT.with_suffix(".d.cts")
AJV_GENERATOR = ROOT / "scripts/contracts/generate_sessions_list_ajv.mjs"


@dataclass(frozen=True)
class Rendered:
    python: str
    python_metadata: str
    typescript: str
    validator_javascript: str
    validator_declarations: str


def _environment() -> dict[str, str]:
    env = dict(os.environ)
    cache_root = Path(tempfile.gettempdir()) / "opensquilla-contract-jsonschema-tools"
    env.setdefault("UV_CACHE_DIR", str(cache_root / "uv"))
    env.setdefault("npm_config_cache", str(cache_root / "npm"))
    env.setdefault("npm_config_update_notifier", "false")
    env.setdefault("npm_config_fund", "false")
    env.setdefault("npm_config_audit", "false")
    return env


def _run(command: list[str], *, env: dict[str, str]) -> None:
    try:
        subprocess.run(
            command,
            cwd=ROOT,
            env=env,
            check=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(f"required code generator is unavailable: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            "sessions.list generation failed; install the pinned dev tools first"
        ) from exc


def _capture(command: list[str], *, env: dict[str, str]) -> str:
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            env=env,
            check=True,
            text=True,
            capture_output=True,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(f"required code generator is unavailable: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            "sessions.list validator generation failed: " + exc.stderr.strip()
        ) from exc
    return completed.stdout


def _header(prefix: str) -> str:
    digest = hashlib.sha256(SCHEMA.read_bytes()).hexdigest()
    generator_digest = hashlib.sha256(
        Path(__file__).read_bytes() + b"\0" + AJV_GENERATOR.read_bytes()
    ).hexdigest()
    return (
        f"{prefix} @generated by scripts/contracts/generate_sessions_list_contract.py; "
        "do not edit.\n"
        f"{prefix} source-sha256: {digest}\n"
        f"{prefix} generator-sha256: {generator_digest}\n"
    )


def _normalise(text: str, *, prefix: str) -> str:
    body = text.replace("\r\n", "\n").rstrip() + "\n"
    lint_directive = "# ruff: noqa\n" if prefix == "#" else ""
    return _header(prefix) + lint_directive + "\n" + body


def _contract_metadata() -> tuple[str, str]:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    method = schema["x-opensquilla-method"]
    name = method["name"]
    scope = method["scope"]
    if not isinstance(name, str) or not isinstance(scope, str):
        raise RuntimeError("sessions.list Contract method metadata must be strings")
    return name, scope


def _python_metadata(*, method: str, scope: str) -> str:
    return _normalise(
        "from typing import Final\n\n"
        + f"SESSIONS_LIST_METHOD: Final = {method!r}\n"
        + f"SESSIONS_LIST_SCOPE: Final = {scope!r}\n",
        prefix="#",
    )


def _with_typescript_metadata(text: str, *, method: str, scope: str) -> str:
    return (
        text.rstrip()
        + "\n\n"
        + f"export const SESSIONS_LIST_METHOD = {json.dumps(method)} as const\n"
        + f"export const SESSIONS_LIST_SCOPE = {json.dumps(scope)} as const\n"
    )


def render() -> Rendered:
    python_runner = [sys.executable, "-m", "datamodel_code_generator"]
    typescript_runner = [
        "npm",
        "--prefix",
        "opensquilla-webui",
        "exec",
        "--",
        "json2ts",
    ]

    env = _environment()
    method, scope = _contract_metadata()
    with tempfile.TemporaryDirectory(prefix="opensquilla-jsonschema-codegen-") as raw_tmp:
        tmp = Path(raw_tmp)
        python_tmp = tmp / "sessions_list.py"
        typescript_tmp = tmp / "sessionsList.ts"

        _run(
            [
                *python_runner,
                "--input",
                str(SCHEMA),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(python_tmp),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.12",
                "--use-standard-collections",
                "--use-union-operator",
                "--use-schema-description",
                "--field-constraints",
                "--strict-types",
                "str",
                "int",
                "float",
                "bool",
                "--formatters",
                "builtin",
                "--disable-timestamp",
            ],
            env=env,
        )
        _run(
            [
                *typescript_runner,
                "--input",
                str(SCHEMA),
                "--output",
                str(typescript_tmp),
                "--unreachableDefinitions",
                "--bannerComment",
                "",
            ],
            env=env,
        )

        return Rendered(
            python=_normalise(
                python_tmp.read_text(encoding="utf-8"),
                prefix="#",
            ),
            python_metadata=_python_metadata(method=method, scope=scope),
            typescript=_normalise(
                _with_typescript_metadata(
                    typescript_tmp.read_text(encoding="utf-8"),
                    method=method,
                    scope=scope,
                ),
                prefix="//",
            ),
            validator_javascript=_normalise(
                _capture(["node", str(AJV_GENERATOR), str(SCHEMA)], env=env),
                prefix="//",
            ),
            validator_declarations=_normalise(
                "export interface ContractValidator {\n"
                "  (value: unknown): boolean\n"
                "  errors?: readonly unknown[] | null\n"
                "}\n\n"
                "export const validateSessionsListRequestFrame: ContractValidator\n"
                "export const validateSessionsListResponseFrame: ContractValidator\n",
                prefix="//",
            ),
        )


def _current(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.exists() else None


def _check(rendered: Rendered) -> int:
    stale: list[Path] = []
    if _current(PYTHON_OUTPUT) != rendered.python:
        stale.append(PYTHON_OUTPUT)
    if _current(PYTHON_METADATA_OUTPUT) != rendered.python_metadata:
        stale.append(PYTHON_METADATA_OUTPUT)
    if _current(TYPESCRIPT_OUTPUT) != rendered.typescript:
        stale.append(TYPESCRIPT_OUTPUT)
    if _current(VALIDATOR_OUTPUT) != rendered.validator_javascript:
        stale.append(VALIDATOR_OUTPUT)
    if _current(VALIDATOR_DECLARATIONS_OUTPUT) != rendered.validator_declarations:
        stale.append(VALIDATOR_DECLARATIONS_OUTPUT)
    if stale:
        for path in stale:
            print(f"stale generated sessions.list Contract artifact: {path}", file=sys.stderr)
        return 1
    return 0


def _write(rendered: Rendered) -> None:
    for path, content in (
        (PYTHON_OUTPUT, rendered.python),
        (PYTHON_METADATA_OUTPUT, rendered.python_metadata),
        (TYPESCRIPT_OUTPUT, rendered.typescript),
        (VALIDATOR_OUTPUT, rendered.validator_javascript),
        (VALIDATOR_DECLARATIONS_OUTPUT, rendered.validator_declarations),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--verify-determinism", action="store_true")
    args = parser.parse_args()

    first = render()
    if args.verify_determinism:
        second = render()
        if first != second:
            print("sessions.list Contract generation is not deterministic", file=sys.stderr)
            return 1
        return 0
    if args.write:
        _write(first)
        return 0
    return _check(first)


if __name__ == "__main__":
    raise SystemExit(main())
