auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules-store

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: opensquilla_index_
        period: 24h

limits_config:
  allow_structured_metadata: true
  retention_period: 336h
  volume_enabled: true

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: filesystem

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  enable_api: true
  evaluation:
    mode: local
  rule_path: /loki/rules-temp
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: inmemory

analytics:
  reporting_enabled: false
