#!/usr/bin/env python3
"""Generate Desktop's offline Router presets from the backend catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUTPUT = ROOT / "desktop/electron/src/generated/desktop-router-catalog.ts"
sys.path.insert(0, str(SRC))

from opensquilla.onboarding.provider_specs import provider_catalog_payload  # noqa: E402
from opensquilla.provider.preset_registry import get_preset  # noqa: E402
from opensquilla.router_tiers import IMAGE_TIER, TEXT_TIERS  # noqa: E402

GENERATED_HEADER = "// @generated by scripts/generate_desktop_router_catalog.py; do not edit."
_TIER_FIELDS = {
    "provider": "provider",
    "model": "model",
    "description": "description",
    "thinking_level": "thinkingLevel",
    "image_only": "imageOnly",
    "ensemble_enabled": "ensembleEnabled",
    "ensemble_selection_mode": "ensembleSelectionMode",
}


def router_profiles() -> dict[str, dict[str, dict[str, Any]]]:
    profiles: dict[str, dict[str, dict[str, Any]]] = {}
    for provider in provider_catalog_payload():
        if not provider["routerSupported"]:
            continue
        provider_id = provider["providerId"]
        preset = get_preset(provider_id)
        if preset is None:
            raise ValueError(f"Router provider {provider_id!r} has no preset")
        tiers = preset.tier_defaults()
        missing = set(TEXT_TIERS) - tiers.keys()
        unknown = tiers.keys() - {*TEXT_TIERS, IMAGE_TIER}
        if missing or unknown:
            raise ValueError(
                f"Router preset {provider_id!r} has invalid tiers: "
                f"missing={sorted(missing)}, unknown={sorted(unknown)}"
            )
        profile: dict[str, dict[str, Any]] = {}
        for name in (*TEXT_TIERS, IMAGE_TIER):
            if name not in tiers:
                continue
            tier = tiers[name]
            if not str(tier.get("provider") or "").strip() or not str(
                tier.get("model") or ""
            ).strip():
                raise ValueError(f"Router preset {provider_id!r} has an empty {name!r} route")
            unknown_fields = tier.keys() - _TIER_FIELDS.keys() - {"supports_image"}
            if unknown_fields:
                raise ValueError(
                    f"Router preset {provider_id!r}/{name} has unsupported fields: "
                    f"{sorted(unknown_fields)}"
                )
            # Gateway owns capability resolution. Desktop no longer writes
            # the preset's legacy supports_image hints as operator overrides.
            profile[name] = {
                target: tier[source]
                for source, target in _TIER_FIELDS.items()
                if source in tier
            }
        profiles[provider_id] = profile
    return profiles


def render() -> str:
    payload = json.dumps(router_profiles(), ensure_ascii=False, indent=2)
    return (
        f"{GENERATED_HEADER}\n\n"
        "import type { RouterTier } from '../router-tier-normalization.js'\n\n"
        "export const ROUTER_PROFILES: Record<string, Record<string, RouterTier>> = "
        f"{payload}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    group.add_argument("--write", action="store_true", help="write the generated catalog")
    args = parser.parse_args()
    rendered = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if args.check:
        if current != rendered:
            print(f"stale generated catalog: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
