"""opensquilla.provider — unified LLM provider abstraction layer."""

from .anthropic import AnthropicProvider
from .credentials import Credential, CredentialPool, NoCredentialsAvailable
from .ensemble import (
    EnsembleMemberConfig,
    EnsembleProvider,
    build_ensemble_provider_from_config,
)
from .failures import (
    ProviderFailureKind,
    ProviderRecoveryAction,
    classify_provider_error,
    decide_recovery_action,
)
from .image_projection import (
    ImageFailureClassification,
    ImageFailureKind,
    ImageInputFailureKind,
    ImageIntent,
    ImageIntentKind,
    ImageMarkerState,
    ImageProjectionDecision,
    ImageProjectionMode,
    ImageProjectionPolicy,
    ImageProjectionResult,
    MediaProjectionResult,
    VisionSupportEvidence,
    VisionSupportSource,
    VisionSupportStatus,
    assert_text_only_messages,
    bind_image_attachment_ids,
    build_image_marker,
    classify_image_failure,
    classify_image_input_error,
    classify_provider_image_error,
    count_image_blocks,
    has_image_blocks,
    image_marker,
    marker_for_image,
    normalize_marker_state,
    normalize_vision_support,
    project_image_messages,
    project_messages,
    project_messages_for_model,
    projection_mode_for_support,
    resolve_vision_support,
)
from .ollama import OllamaProvider
from .openai import OpenAIProvider
from .openai_responses import OpenAIResponsesProvider
from .protocol import (
    LLMProvider,
    ProviderFailure,
    ProviderFinalRequestProjector,
    ProviderMessageCountProjector,
    ProviderMetadata,
    ProviderMetadataProvider,
    ProviderPlugin,
    project_provider_final_request,
    project_provider_message_count,
    provider_metadata,
    resolve_failover_chain,
    resolve_quota_status,
)
from .registry import (
    ProviderSpec,
    UnknownProviderError,
    get_provider_spec,
    list_provider_names,
    list_provider_specs,
)
from .selector import (
    ModelSelector,
    ProviderBuildError,
    ProviderConfig,
    SelectorConfig,
    build_provider,
)
from .smart_routing import RefusalDecision, should_refuse
from .types import (
    ChatConfig,
    ContentBlockCompaction,
    ContentBlockDocument,
    ContentBlockImage,
    ContentBlockRedactedThinking,
    ContentBlockText,
    ContentBlockThinking,
    ContentBlockToolResult,
    ContentBlockToolUse,
    DoneEvent,
    ErrorEvent,
    FailureInjector,
    Message,
    ModelCapabilities,
    ModelInfo,
    ProviderActivityEvent,
    ProviderAttemptFailure,
    ProviderFinalRequestProjection,
    ProviderGenerationResetEvent,
    ProviderHeartbeatEvent,
    ProviderMessageCountProjection,
    ProviderMessageLimitProof,
    ProviderRequestCorrelation,
    QuotaStatus,
    ReasoningDeltaEvent,
    StreamEvent,
    TextDeltaEvent,
    ToolDefinition,
    ToolInputSchema,
    ToolUseDeltaEvent,
    ToolUseEndEvent,
    ToolUseStartEvent,
    VisionSupport,
    derive_provider_request_correlation,
    synthetic_failure_event,
)

__all__ = [
    # Protocol
    "LLMProvider",
    "ProviderPlugin",
    "ProviderFailure",
    "ProviderMetadata",
    "ProviderMetadataProvider",
    "ProviderFinalRequestProjector",
    "ProviderMessageCountProjector",
    "provider_metadata",
    "project_provider_final_request",
    "project_provider_message_count",
    "ProviderFailureKind",
    "resolve_failover_chain",
    "resolve_quota_status",
    "ProviderRecoveryAction",
    "classify_provider_error",
    "decide_recovery_action",
    # Providers
    "AnthropicProvider",
    "OpenAIProvider",
    "OpenAIResponsesProvider",
    "OllamaProvider",
    "EnsembleProvider",
    "EnsembleMemberConfig",
    "build_ensemble_provider_from_config",
    # Registry
    "ProviderSpec",
    "UnknownProviderError",
    "get_provider_spec",
    "list_provider_names",
    "list_provider_specs",
    # Selector
    "ModelSelector",
    "SelectorConfig",
    "ProviderConfig",
    "ProviderBuildError",
    "build_provider",
    # Credentials
    "Credential",
    "CredentialPool",
    "NoCredentialsAvailable",
    # Smart routing
    "RefusalDecision",
    "should_refuse",
    # Types
    "StreamEvent",
    "TextDeltaEvent",
    "ReasoningDeltaEvent",
    "ToolUseStartEvent",
    "ToolUseDeltaEvent",
    "ToolUseEndEvent",
    "DoneEvent",
    "ErrorEvent",
    "ProviderActivityEvent",
    "ProviderHeartbeatEvent",
    "ProviderGenerationResetEvent",
    # Internal coordinator contract; it is intentionally excluded from
    # StreamEvent/public gateway payload unions.
    "ProviderAttemptFailure",
    "ProviderFinalRequestProjection",
    "ProviderMessageCountProjection",
    "ProviderMessageLimitProof",
    "ProviderRequestCorrelation",
    "derive_provider_request_correlation",
    "ModelCapabilities",
    "ModelInfo",
    "VisionSupport",
    "ChatConfig",
    "Message",
    "QuotaStatus",
    "ToolDefinition",
    "ToolInputSchema",
    "ContentBlockText",
    "ContentBlockThinking",
    "ContentBlockRedactedThinking",
    "ContentBlockToolUse",
    "ContentBlockToolResult",
    "ContentBlockCompaction",
    "ContentBlockDocument",
    "ContentBlockImage",
    # Request-local image projection
    "VisionSupportEvidence",
    "VisionSupportSource",
    "VisionSupportStatus",
    "normalize_vision_support",
    "resolve_vision_support",
    "ImageProjectionMode",
    "ImageProjectionPolicy",
    "ImageProjectionDecision",
    "MediaProjectionResult",
    "ImageProjectionResult",
    "ImageIntentKind",
    "ImageIntent",
    "ImageMarkerState",
    "normalize_marker_state",
    "image_marker",
    "build_image_marker",
    "marker_for_image",
    "bind_image_attachment_ids",
    "projection_mode_for_support",
    "project_messages",
    "project_messages_for_model",
    "project_image_messages",
    "count_image_blocks",
    "has_image_blocks",
    "assert_text_only_messages",
    "ImageFailureKind",
    "ImageInputFailureKind",
    "ImageFailureClassification",
    "classify_image_input_error",
    "classify_provider_image_error",
    "classify_image_failure",
    # Test-only failure injection seam
    "FailureInjector",
    "synthetic_failure_event",
]
